blank_issues_enabled: false
 contact_links:
   - name: Create new issue
     url: https://new-issue.vuejs.org/?repo=vuejs/vue-router-next
     about: Please use the following link to create a new issue.
   - name: Github Sponsors
     url: https://github.com/sponsors/posva
     about: Love Vue.js? Please consider supporting us via Github Sponsors.
   - name: Open Collective
     url: https://opencollective.com/vuejs/donate
     about: Love Vue.js? Please consider supporting us via Open Collective.
