blank_issues_enabled: false
contact_links:
  - name: ğŸ‘¨â€ğŸ’» Support
    url: https://cal.com/posva/consultancy
    about: Get direct help from the author of Vue Router with your project
  - name: â“ Help & Questions
    url: https://github.com/vuejs/router/discussions/new?category=help-and-questions
    about: Ask a question or discuss about Vue Router
  - name: ğŸ’¡ Ideas
    url: https://github.com/vuejs/router/discussions/new?category=ideas
    about: Start a discussion to improve Vue Router
  - name: ğŸŒŸ GitHub Sponsors
    url: https://github.com/sponsors/posva
    about: Like this project? Please consider supporting the author.
  - name: Open Collective
    url: https://opencollective.com/vuejs/donate
    about: Love Vue.js? Please consider supporting us via Open Collective.
