name: test

on:
  push:
    paths-ignore:
      - 'packages/docs/**'
      - 'packages/playground/**'
  pull_request:
    paths-ignore:
      - 'packages/docs/**'
      - 'packages/playground/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.1.7
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - run: pnpm install
      # - run: pnpm run lint
      # - run: pnpm run -r test:types
      # - run: pnpm run -r test:unit
      # - run: pnpm run -r build
      # - run: pnpm run -r build:dts
      # - run: pnpm run -r test:dts

      # E2E testing

      - name: 'Start BrowserStackLocal Tunnel'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: 'start'
          local-logging-level: 'all-logs'
          local-identifier: 'random'

      - run: pnpm run -r test:e2e:bs-test

      - name: 'Stop BrowserStackLocal'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: 'stop'

      - run: pnpm run -r test:e2e:ci

      # - uses: codecov/codecov-action@v2
