name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'packages/docs/**'
      - 'packages/playground/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'packages/docs/**'
      - 'packages/playground/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: pnpm
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        # forks do not have access to secrets so just skip this
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run -r build
      - run: pnpm run -r build:dts
      - run: pnpm run -r test:types
      - run: pnpm run -r test:unit

      # e2e tests that that run locally
      - run: pnpm run -r test:e2e:ci

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # - name: 'Start BrowserStackLocal Tunnel'
      #   uses: 'browserstack/github-actions/setup-local@master'
      #   with:
      #     local-testing: 'start'
      #     local-logging-level: 'all-logs'
      #     local-identifier: 'random'

      # - run: pnpm run -r test:e2e:bs-test

      # - name: 'Stop BrowserStackLocal'
      #   uses: 'browserstack/github-actions/setup-local@master'
      #   with:
      #     local-testing: 'stop'
